# Generated by Django 3.2.3 on 2021-06-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_setup_data'),
    ]

    operations = [
        # アプリからデータアクセスを許可する（tenant_usersは必須）
        migrations.RunSQL("""
            GRANT select, insert ON myapp_tenant TO tenantuser;
            GRANT select, insert ON myapp_tenantuser TO tenantuser;
            GRANT select, insert ON myapp_customer TO tenantuser;
            GRANT select, insert ON myapp_tenantuser_groups TO tenantuser;
            GRANT select, insert ON myapp_tenantuser_user_permissions TO tenantuser;
        """,
        reverse_sql="""
            REVOKE select, insert ON myapp_tenant FROM tenantuser;
            REVOKE select, insert ON myapp_tenantuser FROM tenantuser;
            REVOKE select, insert ON myapp_customer FROM tenantuser;
            REVOKE select, insert ON myapp_tenantuser_groups FROM tenantuser;
            REVOKE select, insert ON myapp_tenantuser_user_permissions FROM tenantuser;
        """),
        # RLS設定
        migrations.RunSQL("""
            ALTER TABLE myapp_tenant ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantuser_tenants ON myapp_tenant USING(id::text = current_user);
            ALTER TABLE myapp_tenantuser ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantuser_tenantusers ON myapp_tenantuser USING(tenant_id::text = current_user);
            ALTER TABLE myapp_customer ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantuser_customers ON myapp_customer USING(tenant_id::text = current_user);
        """,
        reverse_sql='''
            ALTER TABLE myapp_tenant DISABLE ROW LEVEL SECURITY;
            DROP POLICY tenantuser_tenants ON myapp_tenant;
            ALTER TABLE myapp_tenantuser DISABLE ROW LEVEL SECURITY;
            DROP POLICY tenantuser_tenantusers ON myapp_tenantuser;
            ALTER TABLE myapp_customer DISABLE ROW LEVEL SECURITY;
            DROP POLICY tenantuser_customers ON myapp_customer;
        ''')
    ]
