# Generated by Django 3.2.3 on 2021-06-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_grant_roles'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('''
            GRANT select, insert, delete ON django_session TO tenantuser;
        ''',
        reverse_sql='''
            REVOKE select, insert, delete ON django_session FROM tenantuser;
        ''')
    ]
