# Generated by Django 3.2.3 on 2021-06-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    def migrate_data(apps, schema_editor):
        AppPermission = apps.get_model('myapp','AppPermission')
        Tenant = apps.get_model('myapp', 'Tenant')

        t1 = Tenant.objects.get(tenant_key='xxx')

        AppPermission.objects.create(tenant=t1, view='admin')
        AppPermission.objects.create(tenant=t1, view='')
        AppPermission.objects.create(tenant=t1, view='app1')
        AppPermission.objects.create(tenant=t1, view='app2')
        AppPermission.objects.create(tenant=t1, view='customer')

        t2 = Tenant.objects.get(tenant_key='yyy')
        AppPermission.objects.create(tenant=t2, view='admin')
        AppPermission.objects.create(tenant=t2, view='')
        AppPermission.objects.create(tenant=t2, view='customer')

    def reverse_data(apps, schema_editor):
        AppPermission = apps.get_model('myapp','AppPermission')
        Tenant = apps.get_model('myapp', 'Tenant')

        t1 = Tenant.objects.get(tenant_key='xxx')
        AppPermission.objects.filter(tenant=t1).delete()
        t2 = Tenant.objects.get(tenant_key='yyy')
        AppPermission.objects.filter(tenant=t2).delete()

    dependencies = [
        ('myapp', '0006_auto_20210621_1114'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data,
            reverse_code=reverse_data
        ),
    ]

